/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303032",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#dec29a",
        "surface-bright": "#fcf8fa",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-tint": "#565e74",
        "surface-glass": "rgba(255, 255, 255, 0.7)",
        "inverse-on-surface": "#f3f0f2",
        "border-glass": "rgba(255, 255, 255, 0.1)",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fffbff",
        "on-tertiary-container": "#98805d",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#574425",
        "primary-container": "#131b2e",
        "surface-variant": "#e4e2e4",
        "on-primary-container": "#7c839b",
        "secondary-container": "#6063ee",
        "on-secondary": "#ffffff",
        "secondary": "#4648d4",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9db",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f5",
        "tertiary-container": "#271901",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#07006c",
        "on-background": "#1b1b1d",
        "outline": "#76777d",
        "primary-fixed-dim": "#bec6e0",
        "tertiary": "#000000",
        "primary": "#000000",
        "border-subtle": "rgba(226, 232, 240, 0.8)",
        "surface-container-high": "#eae7e9",
        "tertiary-fixed": "#fcdeb5",
        "on-surface": "#1b1b1d",
        "secondary-fixed": "#e1e0ff",
        "background": "#fcf8fa",
        "on-error-container": "#93000a",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#271901",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "surface": "#fcf8fa",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2e4",
        "surface-container": "#f0edef"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "section-gap": "4rem",
        gutter: "1.5rem",
        "component-gap": "2rem",
        "margin-desktop": "4rem",
        "margin-mobile": "1.25rem",
        "max-width": "1440px"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      backgroundImage: {
        "ai-purple-gradient": "linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)"
      }
    },
  },
  plugins: [],
}
