/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#c0c1ff",
        "background": "#f7f9fb",
        "border-subtle": "#e2e8f0",
        "tertiary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e1e0ff",
        "outline-variant": "#c6c6cd",
        "secondary-container": "#6063ee",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface-glass": "rgba(255, 255, 255, 0.8)",
        "surface-tint": "#565e74",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-bright": "#f7f9fb",
        "primary-container": "#131b2e",
        "on-primary-container": "#7c839b",
        "ink-muted": "#475569",
        "surface-dim": "#d8dadc",
        "outline": "#76777d",
        "tertiary": "#000000",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-container": "#75859d",
        "surface-container-high": "#e6e8ea",
        "error": "#ba1a1a",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#07006c",
        "primary": "#000000",
        "secondary": "#4648d4",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#0b1c30",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "5rem",
        "container-max": "1440px",
        "component-gap": "3rem",
        "margin-mobile": "1.5rem",
        gutter: "2rem",
        "section-gap": "6rem",
        "margin-tablet": "3rem"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.7", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-xl": ["56px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.8", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }]
      },
      backgroundImage: {
        "ai-purple-gradient": "linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)"
      }
    },
  },
  plugins: [],
}
