// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStay.Data.Context;

#nullable disable

namespace SmartStay.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827160934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartStay.Core.Entities.Listing", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Accommodates")
                        .HasColumnType("int");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Availability365")
                        .HasColumnType("int");

                    b.Property<double>("Bathrooms")
                        .HasPrecision(5, 1)
                        .HasColumnType("float(5)");

                    b.Property<double>("Bedrooms")
                        .HasPrecision(5, 1)
                        .HasColumnType("float(5)");

                    b.Property<double>("Beds")
                        .HasPrecision(5, 1)
                        .HasColumnType("float(5)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<int>("MinimumNights")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NeighbourhoodCleansed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfReviews")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("ReviewScoresRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<double>("ReviewsPerMonth")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NeighbourhoodCleansed");

                    b.HasIndex("Price");

                    b.HasIndex("RoomType");

                    b.ToTable("Listings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
